name: test-flutter
on: [push]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - name: Run Tests
      working-directory: ./chegaja_frontend
      run: flutter test